
---
- name: Create ntfy users
  command: >
    {{ devture_systemd_docker_base_host_command_sh }} -c '{{ devture_systemd_docker_base_host_command_docker }} run \
    --rm \
    --env NTFY_PASSWORD={{ item.password }} \
    --user={{ ntfy_uid }}:{{ ntfy_gid }} \
    --mount type=bind,src={{ ntfy_config_dir_path }},dst=/etc/ntfy,ro \
    --mount type=bind,src={{ ntfy_data_path }},dst=/data \
    --network none \
    {{ ntfy_container_image }} \
    ntfy user add --role={{ item.admin | ternary("admin", "user") }} {{ item.username }}'
  with_items: "{{ ntfy_credentials }}"
  when: ntfy_credentials | length > 0

- name: Write ntfy users passwords
  command: >
    {{ devture_systemd_docker_base_host_command_sh }} -c '{{ devture_systemd_docker_base_host_command_docker }} run \
    --rm \
    --env NTFY_PASSWORD={{ item.password }} \
    --user={{ ntfy_uid }}:{{ ntfy_gid }} \
    --mount type=bind,src={{ ntfy_config_dir_path }},dst=/etc/ntfy,ro \
    --mount type=bind,src={{ ntfy_data_path }},dst=/data \
    --network none \
    {{ ntfy_container_image }} \
    ntfy user change-pass {{ item.username }}'
  with_items: "{{ ntfy_credentials }}"
  when: ntfy_credentials | length > 0

- name: Write ntfy users roles
  command: >
    {{ devture_systemd_docker_base_host_command_sh }} -c '{{ devture_systemd_docker_base_host_command_docker }} run \
    --rm \
    --env NTFY_PASSWORD={{ item.password }} \
    --user={{ ntfy_uid }}:{{ ntfy_gid }} \
    --mount type=bind,src={{ ntfy_config_dir_path }},dst=/etc/ntfy,ro \
    --mount type=bind,src={{ ntfy_data_path }},dst=/data \
    --network none \
    {{ ntfy_container_image }} \
    ntfy user change-role {{ item.username }} {{ item.admin | ternary("admin", "user") }}'
  with_items: "{{ ntfy_credentials }}"
  when: ntfy_credentials | length > 0
